//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace LSF { namespace LampState {

ref class LampStateSignals;

public interface class ILampStateSignals
{
    event Windows::Foundation::TypedEventHandler<LampStateSignals^, LampStateLampStateChangedReceivedEventArgs^>^ LampStateChangedReceived;
};

public ref class LampStateSignals sealed : [Windows::Foundation::Metadata::Default] ILampStateSignals
{
public:
    // Calling this method will send the LampStateChanged signal to every member of the session.
    void LampStateChanged(_In_ Platform::String^ interfaceMemberLampID);

    // This event fires whenever the LampStateChanged signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<LampStateSignals^, LampStateLampStateChangedReceivedEventArgs^>^ LampStateChangedReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<LampStateSignals^, LampStateLampStateChangedReceivedEventArgs^>^ handler) 
        { 
            return _LampStateChangedReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<LampStateSignals^>(sender), safe_cast<LampStateLampStateChangedReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _LampStateChangedReceived -= token; 
        } 
    internal: 
        void raise(LampStateSignals^ sender, LampStateLampStateChangedReceivedEventArgs^ args) 
        { 
            _LampStateChangedReceived(sender, args);
        } 
    }

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallLampStateChangedReceived(_In_ LampStateSignals^ sender, _In_ LampStateLampStateChangedReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _LampStateChangedReceived;

    alljoyn_interfacedescription_member m_memberLampStateChanged;
};

} } } } 
