//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace microsoft { namespace Sample { namespace AllJoynCar {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IAllJoynCarService. Instead, AllJoynCarServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class AllJoynCarServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IAllJoynCarService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarDriveCalledEventArgs^>^ DriveCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarDriveCalledEventArgs^>^ handler) 
        { 
            return _DriveCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AllJoynCarServiceEventAdapter^>(sender), safe_cast<AllJoynCarDriveCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _DriveCalled -= token; 
        } 
    internal: 
        void raise(AllJoynCarServiceEventAdapter^ sender, AllJoynCarDriveCalledEventArgs^ args) 
        { 
            _DriveCalled(sender, args);
        } 
    }

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarGetSpeedRequestedEventArgs^>^ GetSpeedRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarGetSpeedRequestedEventArgs^>^ handler) 
        { 
            return _GetSpeedRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AllJoynCarServiceEventAdapter^>(sender), safe_cast<AllJoynCarGetSpeedRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetSpeedRequested -= token; 
        } 
    internal: 
        void raise(AllJoynCarServiceEventAdapter^ sender, AllJoynCarGetSpeedRequestedEventArgs^ args) 
        { 
            _GetSpeedRequested(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarGetStateRequestedEventArgs^>^ GetStateRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarGetStateRequestedEventArgs^>^ handler) 
        { 
            return _GetStateRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AllJoynCarServiceEventAdapter^>(sender), safe_cast<AllJoynCarGetStateRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetStateRequested -= token; 
        } 
    internal: 
        void raise(AllJoynCarServiceEventAdapter^ sender, AllJoynCarGetStateRequestedEventArgs^ args) 
        { 
            _GetStateRequested(sender, args);
        } 
    }

    // Property Write Events
    event Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarSetSpeedRequestedEventArgs^>^ SetSpeedRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AllJoynCarServiceEventAdapter^, AllJoynCarSetSpeedRequestedEventArgs^>^ handler) 
        { 
            return _SetSpeedRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AllJoynCarServiceEventAdapter^>(sender), safe_cast<AllJoynCarSetSpeedRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _SetSpeedRequested -= token; 
        } 
    internal: 
        void raise(AllJoynCarServiceEventAdapter^ sender, AllJoynCarSetSpeedRequestedEventArgs^ args) 
        { 
            _SetSpeedRequested(sender, args);
        } 
    }

    // IAllJoynCarService Implementation
    virtual Windows::Foundation::IAsyncOperation<AllJoynCarDriveResult^>^ DriveAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ bool interfaceMemberOnOff, _In_ uint32 interfaceMemberDirection);

    virtual Windows::Foundation::IAsyncOperation<AllJoynCarGetSpeedResult^>^ GetSpeedAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AllJoynCarGetStateResult^>^ GetStateAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<AllJoynCarSetSpeedResult^>^ SetSpeedAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 value);

private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _DriveCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetSpeedRequested;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetStateRequested;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _SetSpeedRequested;
};

} } } } 
