//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace microsoft { namespace Sample { namespace AllJoynCar {

public ref class AllJoynCarState sealed
{
public:
    property bool Value1
    {
        bool get() { return m_value1; }
        void set(bool value) { m_value1 = value; }
    }
     
    property uint32 Value2
    {
        uint32 get() { return m_value2; }
        void set(uint32 value) { m_value2 = value; }
    }
     
private:
    bool m_value1;
    uint32 m_value2;
};

public ref class AllJoynMessageArgStructure sealed : Windows::Foundation::Collections::IVector<Platform::Object^>
{
public:
    AllJoynMessageArgStructure()
    {
        m_vector = ref new Platform::Collections::Vector<Platform::Object^>();
    }

    virtual Windows::Foundation::Collections::IIterator<Platform::Object^>^ First()
    {
        return m_vector->First();
    }

    virtual Platform::Object^ GetAt(unsigned int index)
    {
        return m_vector->GetAt(index);
    }

    virtual property unsigned int Size {
        virtual unsigned int get()
        {
            return m_vector->Size;
        }
    }

    virtual bool IndexOf(Platform::Object^ value, unsigned int * index)
    {
        return m_vector->IndexOf(value, index);
    }

    virtual unsigned int GetMany(unsigned int startIndex, Platform::WriteOnlyArray<Platform::Object^>^ items)
    {
        return m_vector->GetMany(startIndex, items);
    }

    virtual Windows::Foundation::Collections::IVectorView<Platform::Object^>^ GetView()
    {
        return m_vector->GetView();
    }

    virtual void SetAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->SetAt(index, value);
    }

    virtual void InsertAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->InsertAt(index, value);
    }

    virtual void Append(Platform::Object^ value)
    {
        return m_vector->Append(value);
    }

    virtual void RemoveAt(unsigned int index)
    {
        return m_vector->RemoveAt(index);
    }

    virtual void RemoveAtEnd()
    {
        return m_vector->RemoveAtEnd();
    }

    virtual void Clear()
    {
        return m_vector->Clear();
    }

    virtual void ReplaceAll(const Platform::Array<Platform::Object^>^ items)
    {
        return m_vector->ReplaceAll(items);
    }

private:
    Platform::Collections::Vector<Platform::Object^>^ m_vector;
};
} } } } 

partial ref class TypeConversionHelpers
{
internal:
    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::microsoft::Sample::AllJoynCar::AllJoynCarState^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::microsoft::Sample::AllJoynCar::AllJoynCarState();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(**)", &argument1, &argument2));

        bool value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "b", &value1));
        (*value)->Value1 = value1;
        uint32 value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "u", &value2));
        (*value)->Value2 = value2;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::microsoft::Sample::AllJoynCar::AllJoynCarState^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "b", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "u", value->Value2));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(**)", argument1, argument2));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);

        return ER_OK;
    }

};
