//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace microsoft { namespace Sample { namespace AllJoynCar {

public interface class IAllJoynCarService
{
public:
    // Implement this function to handle calls to the Drive method.
    Windows::Foundation::IAsyncOperation<AllJoynCarDriveResult^>^ DriveAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ bool interfaceMemberOnOff, _In_ uint32 interfaceMemberDirection);

    // Implement this function to handle requests for the value of the Speed property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<AllJoynCarGetSpeedResult^>^ GetSpeedAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the Speed property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<AllJoynCarSetSpeedResult^>^ SetSpeedAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, uint32 value);

    // Implement this function to handle requests for the value of the State property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<AllJoynCarGetStateResult^>^ GetStateAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } } 
